name: deploy on push production branch
on:
  push:
    branches:
      - prod  

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}  
          username: ${{ secrets.PROD_USER_NAME }}
          port: ${{ secrets.PROD_PORT }}
          key: ${{ secrets.PROD_KEY }}
          source: "./html/**"
          target: "/var/www/html"
          strip_components: 1