name: deploy on push
on:
  push:
    branches:
      - main  # 仅 main 分支推送时触发

jobs:
  deploy-app:
    runs-on: ubuntu-latest  

    steps:
      # 步骤 1：检出代码到工作目录
      - name: Checkout code to build server
        uses: actions/checkout@v4  

      # 步骤 2：通过 SCP 将文件复制到服务器
      - name: Copy files to server
        uses: appleboy/scp-action@master  
        with:
          host: ${{ secrets.HOST }}         
          username: ${{ secrets.SSH_USER_NAME }}  
          port: ${{ secrets.SSH_PORT }}     
          key: ${{ secrets.SSH_KEY }}        # SSH 私钥（从 Secrets 读取）
          source: "./html/*"                 # 要复制的文件路径（本地仓库的 html 目录下所有文件）
          target: "/var/www/html"            # 服务器目标路径（Nginx 默认静态资源目录）
          strip_components: 1    
                    